---
- name: Webhook demo to launch a job template
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: "{{ port | default(5555) }}"
        host: 0.0.0.0
  rules:
    - name: Launch Job Template Rule
      condition: event.payload != ""
      actions:
      - print_event:
          pretty: true
      - run_job_template:
          name: Demo Job Template
          organization: Default
...
