---
- name: Webhook demo to launch a job template
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: "{{ port | default(5555) }}"
        host: 0.0.0.0
  rules:
    - name: Log Event
      condition: true
      action:
        print_event:
          pretty: true
    - name: Launch Job Template Rule
      condition: true
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
...
