- name: Listen for events on a webhook from ServiceNow
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        token: "{{ eda_auth_token }}"
  rules:
    - name: Output ServiceNow Information
      condition: event.meta is definied
      action:
        debug:
